#!/usr/bin/with-contenv sh

# launch consul-template and hook up a graceful haproxy restart (from haproxy docs)
exec consul-template -consul ${CONSUL_URL} \
        -log-level info \
	-template "/consul-template/haproxy.cfg.tmpl:/consul-template/haproxy.cfg:s6-svc -h /var/run/s6/services/haproxy"

