#!/usr/bin/with-contenv sh

# launch consul-template and hook up a graceful haproxy restart (from haproxy docs)
exec consul-template -consul ${CONSUL_URL} \
	-template "/consul-template/haproxy.cfg.tmpl:/consul-template/haproxy.cfg:haproxy -f /consul-template/haproxy.cfg -p /var/run/haproxy.pid -st $(cat /var/run/haproxy.pid)"

